### ISSUE TITLE
Gem Release (3.1.2) is Broken, Version file not Included in Gem (again :()

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-filter-useragent#48]
This is what's causing https://github.com/elastic/logstash/issues/7594, fixing gemspec now

```sh
[2017-07-06T11:10:26,242][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"filter", :name=>"useragent", :path=>"logstash/filters/useragent", :error_message=>"No such file or directory - /home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-filter-useragent-3.1.2-java/lib/../version", :error_class=>Errno::ENOENT, :error_backtrace=>["org/jruby/RubyIO.java:3600:in `read'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-filter-useragent-3.1.2-java/lib/logstash-filter-useragent_jars.rb:4:in `<main>'", "org/jruby/RubyKernel.java:961:in `require'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-filter-useragent-3.1.2-java/lib/logstash/filters/useragent.rb:1:in `<main>'", "org/jruby/RubyKernel.java:961:in `require'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-filter-useragent-3.1.2-java/lib/logstash/filters/useragent.rb:3:in `(root)'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:1:in `(root)'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:156:in `legacy_lookup'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:138:in `lookup'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:180:in `lookup_pipeline_plugin'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/plugin.rb:140:in `<eval>'", "org/jruby/RubyKernel.java:1000:in `eval'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:125:in `plugin'", "(eval):93:in `initialize'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:82:in `initialize'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:191:in `block in initialize'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:341:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:140:in `with_pipelines'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:338:in `block in converge_state'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:325:in `converge_state'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:165:in `converge_state_and_update'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:140:in `with_pipelines'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:163:in `block in converge_state_and_update'", "/home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:89:in `block in execute'"]}
[2017-07-06T11:10:26,258][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any filter plugin named 'useragent'. Are you sure this is correct? Trying to load the useragent filter plugin resulted in this error: Problems loading the requested plugin named useragent of type filter. Error: Errno::ENOENT No such file or directory - /home/armin/src/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/logstash-filter-useragent-3.1.2-java/lib/../version"}
➜  integration git:(7594)                                                                                                                                                               
```

**Comment by original-brownbear** [comment]
fixed
