### ISSUE TITLE
Unknown Setting "source" and "target" after ES7 upgrade

### ISSUE THREAD

**Issue by aadlung** [logstash-plugins/logstash-filter-useragent#57]
Hi,

after upgrading my single-node dev cluster to ES7, I cannot start logstash due to the following error appearing.
I did not change anything in the configuration (except some small changes outside of logstash for ES7 compatibility).

```
[2019-04-12T00:13:05,071][ERROR][logstash.filters.useragent] Unknown setting '"target"' for useragent
[2019-04-12T00:13:05,073][ERROR][logstash.filters.useragent] Unknown setting '"source"' for useragent
[2019-04-12T00:13:05,085][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Something is wrong with your configuration.", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/config/mixin.rb:86:in `config_init'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:126:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:78:in `filter_delegator'", "org/logstash/plugins/PluginFactoryExt.java:248:in `plugin'", "org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:23:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
```

My logstash config files did not change, they're usually looking the following way:
```
filter {
  if [log_type] == "nginx-access" {
    grok {
      patterns_dir => ["/etc/logstash/patterns"]
      match => { "message" => "%{NGINXACCESS}" }
    }
    date {
      # Try to pull the timestamp from the 'timestamp' field (parsed above with
      # grok).
      # The nginx format looks like:            24/Apr/2016:16:17:20 -0400
      # The varnishncsa format looks like:      24/Apr/2016:22:15:06 +0200
      locale => "en"
      timezone => "Europe/Berlin"
      match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
      add_field => { "debug" => "timestampMatched"}
    }
    useragent {
        "source" => "useragent"
        "target" => "useragentinfo"
    mutate {
      convert => {
        "bytes" => "integer"
        "offset" => "integer"
        "response" => "integer"
      }
    }
```

with NGINXACCESS being a basic pattern 
`NGINXACCESS %{IPORHOST:vhost} - %{IPORHOST:clientip} - %{NOTSPACE:user} \[%{HTTPDATE:timestamp}\] "%{WORD:httpmethod} %{URIPATHPARAM:url} %{NOTSPACE:protocol}" %{NUMBER:response} (?:%{WORD:upstreamcache}|-) (?:%{NUMBER:bytes}|-) (?:"(?:%{URI:referrer}|-)"|%{QS:referrer}) %{QS:useragent} (?:%{QS:xforwardedfor}|-) (?:%{WORD:xforwardedproto}|-) (?:%{WORD:scheme}|-)
`

If I remove the useragent filter, it's starting successfully.

I use version 3.2.3, reinstalled it already.
```
# /usr/share/logstash/bin/logstash-plugin list --verbose|grep useragent
logstash-filter-useragent (3.2.3)
```

**Comment by aadlung** [comment]
If I remove the source/target setting, I get the following error:
```
[2019-04-12T09:09:23,287][ERROR][logstash.filters.useragent] Missing a required setting for the useragent filter plugin:

  filter {
    useragent {
      source => # SETTING MISSING
      ...
    }
  }

```

**Comment by aadlung** [comment]
Reading the error helps in this case - I just removed the `"` quotes from the settings, now it's working.
