### ISSUE TITLE
[Test Failure] LRU object identity tests are failing on Logstash 8.x

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-filter-useragent#81]
Specs are failing when run on Logstash `8.x`, as the tests do not account for ECS compatibility:

```
logstash_1_e47ba82d5d7e |   1) LogStash::Filters::UserAgent LRU object identity for the os_major field should be an utf-8 string
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |      NoMethodError:
logstash_1_e47ba82d5d7e |        undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   2) LogStash::Filters::UserAgent LRU object identity for the os_major field should have equivalent values
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: "10"
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        (compared using eql?)
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   3) LogStash::Filters::UserAgent LRU object identity for the os_major field should not have a nil value
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: truthy value
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   4) LogStash::Filters::UserAgent LRU object identity for the patch field should be an utf-8 string
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |      NoMethodError:
logstash_1_e47ba82d5d7e |        undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   5) LogStash::Filters::UserAgent LRU object identity for the patch field should have equivalent values
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: "2454"
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        (compared using eql?)
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   6) LogStash::Filters::UserAgent LRU object identity for the patch field should not have a nil value
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: truthy value
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   7) LogStash::Filters::UserAgent LRU object identity for the os_name field should have equivalent values
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: "Mac OS X"
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        (compared using eql?)
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   8) LogStash::Filters::UserAgent LRU object identity for the os_name field should be an utf-8 string
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |      NoMethodError:
logstash_1_e47ba82d5d7e |        undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   9) LogStash::Filters::UserAgent LRU object identity for the os_name field should not have a nil value
logstash_1_e47ba82d5d7e |      Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |      
logstash_1_e47ba82d5d7e |        expected: truthy value
logstash_1_e47ba82d5d7e |             got: nil
logstash_1_e47ba82d5d7e |      # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   10) LogStash::Filters::UserAgent LRU object identity for the os_minor field should not have a nil value
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: truthy value
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   11) LogStash::Filters::UserAgent LRU object identity for the os_minor field should be an utf-8 string
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |       NoMethodError:
logstash_1_e47ba82d5d7e |         undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   12) LogStash::Filters::UserAgent LRU object identity for the os_minor field should have equivalent values
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "10"
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   13) LogStash::Filters::UserAgent LRU object identity for the major field should be an utf-8 string
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |       NoMethodError:
logstash_1_e47ba82d5d7e |         undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   14) LogStash::Filters::UserAgent LRU object identity for the major field should not have a nil value
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: truthy value
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   15) LogStash::Filters::UserAgent LRU object identity for the major field should have equivalent values
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "45"
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   16) LogStash::Filters::UserAgent LRU object identity for the minor field should have equivalent values
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "0"
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   17) LogStash::Filters::UserAgent LRU object identity for the minor field should not have a nil value
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: truthy value
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   18) LogStash::Filters::UserAgent LRU object identity for the minor field should be an utf-8 string
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |       NoMethodError:
logstash_1_e47ba82d5d7e |         undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   19) LogStash::Filters::UserAgent LRU object identity for the name field should not have a nil value
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: truthy value
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:459:in `block in <main>'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   20) LogStash::Filters::UserAgent LRU object identity for the name field should have equivalent values
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "Chrome"
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:463:in `block in <main>'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   21) LogStash::Filters::UserAgent LRU object identity for the name field should be an utf-8 string
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |       NoMethodError:
logstash_1_e47ba82d5d7e |         undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:471:in `block in <main>'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   22) LogStash::Filters::UserAgent LRU object identity for the device field should have equivalent values
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to eql(value)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "Mac"
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:463:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   23) LogStash::Filters::UserAgent LRU object identity for the device field should not have a nil value
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field).to be_truthy
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: truthy value
logstash_1_e47ba82d5d7e |              got: nil
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:459:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   24) LogStash::Filters::UserAgent LRU object identity for the device field should be an utf-8 string
logstash_1_e47ba82d5d7e |       Failure/Error: expect(target_field.encoding.name).to eql 'UTF-8'
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |       NoMethodError:
logstash_1_e47ba82d5d7e |         undefined method `encoding' for nil:NilClass
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:471:in `block in /usr/share/plugins/plugin/spec/filters/useragent_spec.rb'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   25) LogStash::Filters::UserAgent Replace source with target "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.31 (K..." processes events as specified
logstash_1_e47ba82d5d7e |       Failure/Error: expect( subject.get("[message][os]") ).to eql "Linux"
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected: "Linux"
logstash_1_e47ba82d5d7e |              got: {"full"=>"Linux", "name"=>"Linux"}
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         (compared using eql?)
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         Diff:
logstash_1_e47ba82d5d7e |         @@ -1,2 +1,3 @@
logstash_1_e47ba82d5d7e |         -"Linux"
logstash_1_e47ba82d5d7e |         +"full" => "Linux",
logstash_1_e47ba82d5d7e |         +"name" => "Linux",
logstash_1_e47ba82d5d7e |         
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:490:in `block in <main>'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e |   26) LogStash::Filters::UserAgent non-exact UA data "Prefix DATA! Mozilla/5.0 (Android 11; Mobile; rv:68..." processes events as specified
logstash_1_e47ba82d5d7e |       Failure/Error: expect( subject.get('user_agent') ).to include "name" => "Firefox Mobile", "version" => '86.0', "os_name" => "Android"
logstash_1_e47ba82d5d7e |       
logstash_1_e47ba82d5d7e |         expected {"device" => {"name" => "Generic Smartphone"}, "name" => "Firefox Mobile", "os" => {"full" => "Android 11", "name" => "Android", "version" => "11"}, "version" => "86.0"} to include {"os_name" => "Android"}
logstash_1_e47ba82d5d7e |         Diff:
logstash_1_e47ba82d5d7e |         
logstash_1_e47ba82d5d7e |         @@ -1,4 +1,5 @@
logstash_1_e47ba82d5d7e |         +"device" => {"name"=>"Generic Smartphone"},
logstash_1_e47ba82d5d7e |          "name" => "Firefox Mobile",
logstash_1_e47ba82d5d7e |         -"os_name" => "Android",
logstash_1_e47ba82d5d7e |         +"os" => {"full"=>"Android 11", "name"=>"Android", "version"=>"11"},
logstash_1_e47ba82d5d7e |          "version" => "86.0",
logstash_1_e47ba82d5d7e |         
logstash_1_e47ba82d5d7e |       # ./spec/filters/useragent_spec.rb:380:in `block in <main>'
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e | Finished in 38.95 seconds (files took 10.85 seconds to load)
logstash_1_e47ba82d5d7e | 86 examples, 26 failures
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e | Failed examples:
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:3:4]' # LogStash::Filters::UserAgent LRU object identity for the os_major field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:3:2]' # LogStash::Filters::UserAgent LRU object identity for the os_major field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:3:1]' # LogStash::Filters::UserAgent LRU object identity for the os_major field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:8:4]' # LogStash::Filters::UserAgent LRU object identity for the patch field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:8:2]' # LogStash::Filters::UserAgent LRU object identity for the patch field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:8:1]' # LogStash::Filters::UserAgent LRU object identity for the patch field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:2:2]' # LogStash::Filters::UserAgent LRU object identity for the os_name field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:2:4]' # LogStash::Filters::UserAgent LRU object identity for the os_name field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:2:1]' # LogStash::Filters::UserAgent LRU object identity for the os_name field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:4:1]' # LogStash::Filters::UserAgent LRU object identity for the os_minor field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:4:4]' # LogStash::Filters::UserAgent LRU object identity for the os_minor field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:4:2]' # LogStash::Filters::UserAgent LRU object identity for the os_minor field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:6:4]' # LogStash::Filters::UserAgent LRU object identity for the major field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:6:1]' # LogStash::Filters::UserAgent LRU object identity for the major field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:6:2]' # LogStash::Filters::UserAgent LRU object identity for the major field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:7:2]' # LogStash::Filters::UserAgent LRU object identity for the minor field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:7:1]' # LogStash::Filters::UserAgent LRU object identity for the minor field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:7:4]' # LogStash::Filters::UserAgent LRU object identity for the minor field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:1:1]' # LogStash::Filters::UserAgent LRU object identity for the name field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:1:2]' # LogStash::Filters::UserAgent LRU object identity for the name field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:1:4]' # LogStash::Filters::UserAgent LRU object identity for the name field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:5:2]' # LogStash::Filters::UserAgent LRU object identity for the device field should have equivalent values
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:5:1]' # LogStash::Filters::UserAgent LRU object identity for the device field should not have a nil value
logstash_1_e47ba82d5d7e | rspec './spec/filters/useragent_spec.rb[1:9:5:4]' # LogStash::Filters::UserAgent LRU object identity for the device field should be an utf-8 string
logstash_1_e47ba82d5d7e | rspec ./spec/filters/useragent_spec.rb:487 # LogStash::Filters::UserAgent Replace source with target "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.31 (K..." processes events as specified
logstash_1_e47ba82d5d7e | rspec ./spec/filters/useragent_spec.rb:378 # LogStash::Filters::UserAgent non-exact UA data "Prefix DATA! Mozilla/5.0 (Android 11; Mobile; rv:68..." processes events as specified
logstash_1_e47ba82d5d7e | 
logstash_1_e47ba82d5d7e | Randomized with seed 28727
logstash_1_e47ba82d5d7e | 
```

**Comment by robbavey** [comment]
Closing - tests are now passing
